### ISSUE TITLE
This is not an issue...

### ISSUE THREAD

**Issue by davehodg** [moznion/aws-lambda-perl5-layer#1]
Thank you so much for something incredibly useful. Can you please expand on the documentation, please? There are SWS terms that you just throw out there that don't mean anything to us that are still working through the starter Cloud Practitioner stuff.

Thanks!

**Comment by moznion** [comment]
I've just rewritten the documentation of this repository and [moznion/aws-lambda-perl5-layer-example](https://github.com/moznion/aws-lambda-perl5-layer-example).
Please feel free to ask (or send a patch 😄) me if you feel the documentation is not clear.

Thank you.
