### ISSUE TITLE
Not an issue. Add any perl file to lambda folder.

### ISSUE THREAD

**Issue by dknty11** [moznion/aws-lambda-perl5-layer#3]
I'd like to ask how can we add any perl file to lambda folder?

**Comment by moznion** [comment]
You only have to include perl file(s) into your function's zip file.
Maybe [moznion/aws-lambda-perl5-layer-example](https://github.com/moznion/aws-lambda-perl5-layer-example) helps you; please refer to the following files:

- [plack/build.sh](https://github.com/moznion/aws-lambda-perl5-layer-example/blob/5d873632f3d2d0c14510a41e4aced014299c7f25/plack/build.sh)
  - this script packs function components (i.e. all of the files that are under the directory) as a zip file
- [plack/Makefile](https://github.com/moznion/aws-lambda-perl5-layer-example/blob/5d873632f3d2d0c14510a41e4aced014299c7f25/plack/Makefile#L17)
  - this Makefile kicks a build.sh
