### ISSUE TITLE
Compatibility with Amazon Linux OS version 2018.03

### ISSUE THREAD

**Issue by suriya** [moznion/aws-lambda-perl5-layer#5]
Is this layer compatible with Amazon Linux OS version 2018.03? https://aws.amazon.com/blogs/compute/upcoming-updates-to-the-aws-lambda-execution-environment/

If not, could you please re-build the layer?

**Comment by moznion** [comment]
I'm so sorry to have kept you waiting.
I've published new this Layers, could you please check it out?

- arn:aws:lambda:ap-northeast-1:652718333417:layer:perl-5_26-layer:4
- arn:aws:lambda:ap-northeast-1:652718333417:layer:perl-5_28-layer:2
- arn:aws:lambda:ap-northeast-1:652718333417:layer:perl-5_30-layer:1
